// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD3ngFxvlVl716mg5FrtJ3QgWaflHL-DU',
    appId: '1:757937816053:web:927cec857948912fcc20bc',
    messagingSenderId: '757937816053',
    projectId: 'fittruck-28864',
    authDomain: 'fittruck-28864.firebaseapp.com',
    storageBucket: 'fittruck-28864.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFK07_FTBBQQQLz1rbIhMJc-h1lNWUTy0',
    appId: '1:757937816053:android:b726b546643e06eecc20bc',
    messagingSenderId: '757937816053',
    projectId: 'fittruck-28864',
    storageBucket: 'fittruck-28864.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCipwRzFDiy4MLKTSySuW3i7fWDLM75JR4',
    appId: '1:757937816053:ios:53c88ec69fad2df7cc20bc',
    messagingSenderId: '757937816053',
    projectId: 'fittruck-28864',
    storageBucket: 'fittruck-28864.firebasestorage.app',
    iosBundleId: 'com.example.flutterProgramacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCipwRzFDiy4MLKTSySuW3i7fWDLM75JR4',
    appId: '1:757937816053:ios:53c88ec69fad2df7cc20bc',
    messagingSenderId: '757937816053',
    projectId: 'fittruck-28864',
    storageBucket: 'fittruck-28864.firebasestorage.app',
    iosBundleId: 'com.example.flutterProgramacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD3ngFxvlVl716mg5FrtJ3QgWaflHL-DU',
    appId: '1:757937816053:web:97c4708060e9e283cc20bc',
    messagingSenderId: '757937816053',
    projectId: 'fittruck-28864',
    authDomain: 'fittruck-28864.firebaseapp.com',
    storageBucket: 'fittruck-28864.firebasestorage.app',
  );

}